### ISSUE TITLE
panic in goroutine, `rmsg` is nil

### ISSUE THREAD

**Issue by bradleyjkemp** [domainr/dnsr#126]
I'm getting a nil panic from this line: https://github.com/domainr/dnsr/blob/aa0c407380cca31a2095753a07874896c2bee6ed/resolver.go#L374
Because this occurs in a goroutine spawned by this library, it's not recoverable

Full trace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1066173]

goroutine 22668 [running]:
github.com/domainr/dnsr.(*Resolver).exchangeIP(0xc0011de090, {0x481cb28, 0xc003b10c30}, {0xc0055ffa28, 0x13}, {0xc01925a140, 0xe}, {0xc0055ff668, 0x12}, {0x1f3bc0a, ...}, ...)
   /root/.cache/go-build/github.com/domainr/dnsr@v0.0.0-20240408100013-aa0c407380cc/resolver.go:374 +0x6b3
github.com/domainr/dnsr.(*Resolver).exchange(0xc0011de090, {0x481cb28, 0xc003b10c30}, {0xc0055ffa28, 0x13}, {0xc0055ff668, 0x12}, {0x1f3bc0a, 0x3}, 0x1)
   /root/.cache/go-build/github.com/domainr/dnsr@v0.0.0-20240408100013-aa0c407380cc/resolver.go:294 +0x185
github.com/domainr/dnsr.(*Resolver).iterateParents.func1({0xc0055ffa28?, 0xc001f8aa20?})
   /root/.cache/go-build/github.com/domainr/dnsr@v0.0.0-20240408100013-aa0c407380cc/resolver.go:235 +0x89
created by github.com/domainr/dnsr.(*Resolver).iterateParents in goroutine 19692
   /root/.cache/go-build/github.com/domainr/dnsr@v0.0.0-20240408100013-aa0c407380cc/resolver.go:234 +0x9ae
```

I've not managed to reliably reproduce it but I'm reasonably sure the bug comes from these lines https://github.com/domainr/dnsr/blob/aa0c407380cca31a2095753a07874896c2bee6ed/resolver.go#L354-L359

The `err` return from `client.ExchangeWithConnContext` is never checked because it's been shadowed by line 354

This means that resolvers with `dnsr.WithTCPRetry()` can panic if:
1. UDP lookup is truncated
2. TCP connection succeeds but lookup fails

In this case, the error check is ineffective at guarding against nil `rmsg` values because the error from the TCP lookup has been lost to the shadowed `err` var https://github.com/domainr/dnsr/blob/aa0c407380cca31a2095753a07874896c2bee6ed/resolver.go#L369-L371

**Comment by cee-dub** [comment]
Thanks for the report and digging in to investigate!

**Comment by cee-dub** [comment]
It does appear there are possible gaps in error handling in this area: https://github.com/domainr/dnsr/blob/aa0c407380cca31a2095753a07874896c2bee6ed/resolver.go#L337-L369

**Comment by case-fastly** [comment]
@bradleyjkemp apologies for the long delay here, we fixed this in #190.
